name: Trigger auto deployment for gym-app-dev-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/gym-app-dev-container-AutoDeployTrigger-32cf1d8f-3638-482f-b94c-555099c84dd5.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.GYMAPPDEVCONTAINER_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: gymappregistry.azurecr.io
          registryUsername: ${{ secrets.GYMAPPDEVCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GYMAPPDEVCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: gym-app-dev-container
          resourceGroup: rg-gym-app
          imageToBuild: gymappregistry.azurecr.io/gym-app-dev-container:${{ github.sha }}
          dockerfilePath: Dockerfile

     

